import Head from 'next/head'
import Image from 'next/image'
import Contact from '../components/contact'
import Exterior from '../components/exterior'
import Header from '../components/header'
import Inside from '../components/inside'
import Perform from '../components/perform'
import Safety from '../components/safety'
import Services from '../components/services'
import New from '../components/new'
import { theme } from './theme';
import { AppBar, Box, Container, CssBaseline, ThemeProvider, Toolbar, Typography,responsiveFontSizes } from '@material-ui/core';


let Theme = responsiveFontSizes(theme);


export default function Home() {
  return (
    <div >
      <Head>
        <title>LAND CRUISER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <ThemeProvider theme={Theme}>
      <Header />
      <New />
      <Services />
      <Safety />
      <Exterior />
      <Perform />
      <Inside />
      <Contact />
    </ThemeProvider> 
    </div>
  )
}
