import Head from 'next/head'
import Contact from '../components/contact/contact'
import Exterior from '../components/exterior/exterior'
import Header from '../components/header/header'
import Inside from '../components/inside/inside'
import Perform from '../components/perform/perform'
import Safety from '../components/safety/safety'
import Services from '../components/services/services'
import New from '../components/new/new'
import { theme } from '../utils/theme';
import { ThemeProvider,responsiveFontSizes } from '@material-ui/core';


let Theme = responsiveFontSizes(theme);


export default function Home() {
  return (
    <div >
      <Head>
        <title>LAND CRUISER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <ThemeProvider theme={Theme}>
      <Header />
      <New />
      <Services />
      <Safety />
      <Exterior />
      <Perform />
      <Inside />
      <Contact />
    </ThemeProvider> 
    </div>
  )
};


